### ISSUE TITLE
can‘t access index page！in china

### ISSUE THREAD

**Issue by shang7053** [quantifind/KafkaOffsetMonitor#112]
In China,google is dead!
when I access the index page,It's show
172.16.41.152/:17 GET http://ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular.js net::ERR_CONNECTION_TIMED_OUT
172.16.41.152/:18 GET http://ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular-route.js net::ERR_CONNECTION_TIMED_OUT
172.16.41.152/:19 GET http://ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular-resource.js net::ERR_CONNECTION_TIMED_OUT

**Comment by plutoid** [comment]
I suggest you scratch the files you have listed  and modify the index page  and rebuild the package, then it will work, hope this help.

**Comment by plutoid** [comment]
you could try this version once I built it.
https://mega.nz/#!dqIAhLoT!Myjp1TN-Wq_FTwaDGGHOQN_seRzr0-hfUWxDshkMJwg

**Comment by VictorZeng** [comment]
see https://github.com/VictorZeng/KafkaOffsetMonitor/releases/tag/v0.2.1-Intranet

**Comment by VictorZeng** [comment]
support 0.9.x https://github.com/DarkPhoenixs/kafka-offset-monitor/releases/tag/0.4.2

**Comment by shang7053** [comment]
@plutoid @dzyangxi @VictorZeng Thanks ! sory for late answer!

**Comment by luoguohao** [comment]
cool.
