### ISSUE TITLE
Is not "0.11" version supported?

### ISSUE THREAD

**Issue by taetaetae** [quantifind/KafkaOffsetMonitor#118]
In "0.11" version, it does not seem to be activated as shown below.
![image](https://user-images.githubusercontent.com/10969354/32314325-ad2e39b6-bfea-11e7-85e5-a5be015e215b.png)

Note that "kafka" is working normally and "producer" and "consumer" are working well.

help me...

**Comment by hsaif** [comment]
Same here!
