### ISSUE TITLE
Grouping does not show grouping by program consumption, only the console-consumer

### ISSUE THREAD

**Issue by 15135936362** [quantifind/KafkaOffsetMonitor#123]
**english:**
I use a Java program to consume in kafka's message, my custom a group to consume these messages, can display the custom on kafkamanager group, in a production environment, we are all custom grouping to spend this console - consume useless for us, just a manual test.Please help me.thank youIf the new version has this feature, please help me.
**chinese:**
我用java程序来消费kafka里的消息，我自定义了一个分组来消费这些消息，在kafkamanager上就能显示自定义的分组，在生产环境中我们都是自定义分组去消费的，这个console-consume对我们来说没用的，只是手动测试一下。有人了解这个问题嘛，请帮帮我。谢谢。如果新的版本有这个功能，麻烦帮我一下。

**Comment by suhzh** [comment]
老哥，下面中文露底啦
