### ISSUE TITLE
New ZK connection built with each REST api request

### ISSUE THREAD

**Issue by emmanuelidi** [quantifind/KafkaOffsetMonitor#21]
It appears that the OffsetGetterWeb constructs a new ZkClient with each GET request. 

Normally, ZK sessions are long-lived so there is value in amortizing connection setup costs over the life of the app. Re-using the ZkClient should also allow for higher number of API requests per unit time. 

I noticed the issue when testing against a modern version of ZooKeeper. Since the ZK libs used by KafkaOffsetMonitor are pre-3.4.0 (and the introduction of the "readOnly" protocol flag), a large number of log messages are being spewed out due to some unfortunate logging code in the ZooKeeper project[1]. 

There doesn't appear to be a reason why the ZkClient needs to be rebuilt per request. Would you accept a PR with a change to re-use ZkClients connections?

[1] https://github.com/apache/zookeeper/blob/release-3.4.6/src/java/main/org/apache/zookeeper/server/ZooKeeperServer.java#L822

**Comment by Mortimerp9** [comment]
will merge the PR after getting the contributor's agreement :)

**Comment by emmanuelidi** [comment]
Thanks. Agreement sent.
