### ISSUE TITLE
Stats Export

### ISSUE THREAD

**Issue by Xorlev** [quantifind/KafkaOffsetMonitor#27]
Hey guys,

I modified the app to export data every interval to StatsD. I'm curious if this is something you'd like to support in mainline, if so I can clean it up, make it pluggable, and turn it into a PR to get some feedback from you.

**Comment by Mortimerp9** [comment]
#58 solves this, please checkout this awesome PR!

**Comment by Xorlev** [comment]
Great! Thank you.
