### ISSUE TITLE
any possibility to add email alert function?

### ISSUE THREAD

**Issue by jerryzh168** [quantifind/KafkaOffsetMonitor#35]
Thanks for the nice tool. It's much easier to monitor kafka with this tool. In the meanwhile, I feel that actually monitoring is not enough for kafka, since people normally won't sit there and stare at the statistics all day. So, I wonder if you could add an email alert functionality(or tell me how to do that), which takes a configuration file and send emails when that topic doesn't emit messages for a specified time. In the configuration file, we should be able to configure topics, email addresses and time intervals to check the status. Is that possible for this project? Thanks!

**Comment by Mortimerp9** [comment]
We internally thought about this at Quantifind, and came to the conclusion that we did not want to reinvent the wheel. Our solution is to use an nrpe/nagios plugin that will notify us when the lags of particular queues becomes worrisome or when a queue should be growing but is not.

Check out these [nrpe plugins](https://gist.github.com/Mortimerp9/62277f79682ec612b75d) 
and [Nagios doc](http://exchange.nagios.org/directory/Addons/Monitoring-Agents/NRPE--2D-Nagios-Remote-Plugin-Executor/details) on how to set it up.

**Comment by Mortimerp9** [comment]
you could probably implement this with the new report plugin system, check #58.
