### ISSUE TITLE
--retain and --refresh types

### ISSUE THREAD

**Issue by Dinoshauer** [quantifind/KafkaOffsetMonitor#38]
Is it possible to set --retain/--refresh (basically the types that takes a .type annotation) to something else than .days and .seconds? I tried setting ``--retain 2.hours`` and restarted the process, but the charts still shows data from yesterday. There were no exceptions when I changed the type though

**Comment by Mortimerp9** [comment]
2.hours should be valid (it should support all the duration types supported by scala's `Duration`). There has been some report of retain not working properly in some cases, maybe this is the case.

**Comment by mazhechao** [comment]
I set 3.days, but the charts still shows data over 3 days ago.

2015-01-29 9:32 GMT+08:00 Pierre Andrews <notifications@github.com>:

> 2.hours should be valid (it should support all the duration types
> supported by scala's Duration). There has been some report of retain not
> working properly in some cases, maybe this is the case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quantifind/KafkaOffsetMonitor/issues/38#issuecomment-71953021>
> .
>



-- 
马哲超
为了理想我宁愿忍受寂寞，饮尽那份孤独。

**Comment by Mortimerp9** [comment]
I can't really reproduce this. Do you see any exceptions in the logs? maybe it's due to #28

**Comment by Dinoshauer** [comment]
I honestly don't know, as I upgraded to 0.8.2.0 and now any sort of list seems to load forever. Sorry I can't be of more assistance

**Comment by Mortimerp9** [comment]
Thanks for the feedback, I'll let you know if I find a fix.

**Comment by ngaya-ll** [comment]
The app deletes old data at the same frequency as the retention interval.  So the amount of data retained will be between 1-2x the configured retention.
