### ISSUE TITLE
Improvement: scale graphs to show greater detail

### ISSUE THREAD

**Issue by allanwax** [quantifind/KafkaOffsetMonitor#42]
Currently the offset position graph has an origin of zero.  When the position is in the millions, the change in offset turns out to be a straight line always, when the change is in the hundreds or thousands.

Scaling the origin and max of the graph to encompass the range of changes, rather than just the absolute value would be more usefull.  That is, use the same number of divisions as it is currently but label it with appropriate numbers from the min to the max.  By that I mean if the min is 120 and the max is 175 then you _might_ have the lowest graph line be 100, each additional graph line increments by 5, until it reaches the top of the graph.

**Comment by Mortimerp9** [comment]
this is already the case, the y scale is set based on the min/max values.

![screen shot 2015-02-13 at 12 15 50](https://cloud.githubusercontent.com/assets/628467/6194539/2dce78b8-b37a-11e4-9f21-0ddd584d012f.png)

**Comment by Mortimerp9** [comment]
try zooming on a smaller time period to see it in action.

**Comment by allanwax** [comment]
My issue was observed within an hour of starting it up.  I'll wait a day and see.

**Comment by Mortimerp9** [comment]
you might have a low point at the beginning maybe. Try moving the sliders
in the overview block at the bottom to zoom on a particular timeframe.
