### ISSUE TITLE
Assembly doesn't appear to include slf4j binding

### ISSUE THREAD

**Issue by emmanuelidi** [quantifind/KafkaOffsetMonitor#43]
Without a binding on the class path, the NoOp binding will be used causing slf4j log events to not be logged. Is this intentional?

Given the inclusion of log4j, the project appears to want to use the `slf4j-log4j12` binding.

**Comment by Mortimerp9** [comment]
Thanks for reporting this. slf4j is good for this, you can add the jar on the classpath at the same time as the offsetmonitor and get it to log. I don't think that it's worth adding it to the assembly.
