### ISSUE TITLE
support for zookeeper chroot

### ISSUE THREAD

**Issue by sokratisg** [quantifind/KafkaOffsetMonitor#50]
Is there any support for zookeeper chrooted setups?

So far, all High Level Consumer kafka clients support zookeeper chrooted setups (i.e. /\<chroot path\>/\<brokers,consumers,etc\>). This is easily achievable through the following zk connect string:
host1:2181,host2:2181,host3:2181/\<chroot path\>

Unfortunately I haven't found a way to set the chroot path in your configuration and also I haven't seen it mentioned anywhere in the src code. Do you have any plans supporting it?

**Comment by Mortimerp9** [comment]
I have never tested it but if you check other bug reports, some have managed to do it by passing the root path in the zk connections parameter:
`... --zk zk-server1,zk-server2/chrootpath`
