### ISSUE TITLE
Pluggable lag metrics storage (Graphite etc)

### ISSUE THREAD

**Issue by adamdubiel** [quantifind/KafkaOffsetMonitor#53]
I think it would be useful to be able to change storage type - SQLite is great and easy to use, but we would like to store lag data in Graphite (so we can have some monitoring there). I imagine two ways of achieving this:

* simply adding graphite support (dropwiazrd metrics?) to core, with on/off flag
* making storage pluggable, i.e. possibility to point to class that implements storage interface

The latter is probably bit more complicated, but still doable. What do you think? Once i get an opinion, i would like to prepare a pull-request.

**Comment by Mortimerp9** [comment]
Thanks for the proposal, there has been previous requests like this in the past. My suggestion at the time, for a quick solution, is to use the command line version of the tool [OffsetGetterApp](https://github.com/quantifind/KafkaOffsetMonitor/blob/master/src/main/scala/com/quantifind/kafka/offsetapp/OffsetGetterApp.scala) on a cron and pipe this to graphite or other log systems. 

I think that it would be good to leave the core dependent on as little outside services as possible, but if you feel like going the plugin ways though, that would be awesome, but as you said, it's could end up being a lot of work.

**Comment by adamdubiel** [comment]
I've seen the discussion about Nagios in closed issues and we are going to adapt this ad-hoc probably, but for long term solution i will try to add some pluggable solution. Since i already know how to work with this, feel free to close this issue and i will create a pull request when i'm ready :)

**Comment by adamdubiel** [comment]
Just to let you know - my colleague is working on PR that will solve this task, i think he will be able to finish it next week, along with Graphite module (in our repository).

**Comment by Mortimerp9** [comment]
That's awesome, thank you!

**Comment by Mortimerp9** [comment]
#58 solves this, please checkout this awesome PR!
