### ISSUE TITLE
why not update？

### ISSUE THREAD

**Issue by mosesyou** [quantifind/KafkaOffsetMonitor#95]
It seems not support 0.10

**Comment by Mortimerp9** [comment]
PR welcome

**Comment by rcasey212** [comment]
@mosesyou @Mortimerp9 Working on it.  See: https://github.com/rcasey212/KafkaOffsetMonitor

**Comment by rcasey212** [comment]
@Mortimerp9 Will you still accept PRs to this project?

**Comment by rcasey212** [comment]
@mosesyou @Mortimerp9 PR submitted which should support Kafka 0.9+  https://github.com/quantifind/KafkaOffsetMonitor/pull/107.
